spring:
  main:
    allow-bean-definition-overriding: true

quickfixj:
  client:
    jmx-enabled: true
    log-factory: slf4j
    message-store-factory: noop
    configString: |
      [default]
      BeginString=FIXT.1.1
      DefaultApplVerID=FIX.5.0SP2
      UseDataDictionary=Y
      TransportDataDictionary=FIXT11.xml
      AppDataDictionary.FIX.5.0SP2=FIX50SP2.modified.xml
      
      SocketUseSSL=N

      ResetOnLogon=Y
      ResetOnLogout=Y
      ResetOnDisconnect=Y
      ValidateUnorderedGroupFields=N
      ValidateUserDefinedFields=N
      ValidateFieldsOutOfOrder=N
      AllowUnknownMsgFields=Y
      CheckLatency=N
      HeartBtInt=30
      PersistMessages=N
      SLF4JLogEventCategory=quickfix.events
      SLF4JLogIncomingMessageCategory=${targetCompID}.${senderCompID}.incoming
      SLF4JLogOutgoingMessageCategory=${targetCompID}.${senderCompID}.outgoing
      SLF4JLogPrependSessionID=N
      SLF4JLogHeartbeats=Y
      
      ConnectionType=initiator
      ReconnectInterval=5
      
      [session]
      SenderCompID=????
      TargetCompID=????

      #SocketConnectHost=localhost
      SocketConnectHost=????
      SocketConnectPort=????
      
      LogonTag=553=${app.session.username}
      LogonTag1=554=${app.session.password}
      TimeZone=Europe/London
      StartTime=24:00:00
      EndTime=23:55:00

server:
  port: 8081

app:
  session:
    username: ????
    password: ????
  filter:
    # filters are additive
    # instruments not matching all the specified filter criteria are omitted
    # filter criteria may be left blank
    underlyingSymbols:
    products: # In this version of the application only the first product specified will be evaluated
      - 102 # EVENTS
    symbolRegularExpressions:
      - .*NFL-W8* # NFL 'week 8' event contracts
    periods: # I, D, W, M, O
    securitySubTypes:
logging:
  group:
    fix: quickfix.ThreadedSocketInitiator, quickfixj.msg.incoming, quickfixj.msg.outgoing
    nadex: com.nadex
    allune: com.allune
  level:
    fix: INFO
    nadex: DEBUG
    allune: INFO

management:
  endpoint:
    quickfixjclient:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjclient
